name: Setup

runs:
  using: composite

  steps:
    - name: Install Foundry
      uses: foundry-rs/foundry-toolchain@v1
    - name: Enable Corepack
      shell: bash
      run: corepack enable
    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 18
        cache: 'pnpm'
    - name: Set up pnpm via Corepack
      shell: bash
      run: corepack prepare pnpm@9.0.6 --activate
    - name: Install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile
