name: Setup

runs:
  using: composite

  steps:
    - name: Install system dependencies
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y libudev-dev libusb-1.0-0-dev
    - name: Enable corepack for modern yarn
      shell: bash
      run: corepack enable
    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'yarn'
    - name: Install dependencies
      shell: bash
      run: yarn --immutable
