packages:
  - packages/*
  - packages/*/*

catalog:
  '@changesets/cli': ^2.29.7
  '@commitlint/cli': ^20.1.0
  '@commitlint/config-conventional': ^20.0.0
  '@eslint/js': ^9.37.0
  '@graphprotocol/sdk': ^0.6.1
  '@nomicfoundation/hardhat-chai-matchers': ^2.0.0
  '@nomicfoundation/hardhat-ethers': ^3.1.0
  '@nomicfoundation/hardhat-foundry': ^1.1.1
  '@nomicfoundation/hardhat-ignition': 0.15.9
  '@nomicfoundation/hardhat-ignition-ethers': 0.15.9
  '@nomicfoundation/hardhat-network-helpers': ^1.0.9
  '@nomicfoundation/hardhat-toolbox': ^5.0.0
  '@nomicfoundation/hardhat-verify': ^2.0.10
  '@nomicfoundation/ignition-core': 0.15.9
  '@openzeppelin/contracts': ^5.3.0
  '@typechain/ethers-v5': ^10.2.1
  '@typechain/hardhat': ^9.0.0
  '@types/debug': ^4.1.12
  '@types/json5': ^2.2.0
  '@types/node': ^20.17.50
  '@typescript-eslint/eslint-plugin': ^8.46.1
  '@typescript-eslint/parser': ^8.46.1
  '@wagmi/cli': ^2.3.1
  chai: ^4.2.0
  debug: ^4.4.0
  dotenv: ^16.5.0
  eslint: ^9.37.0
  eslint-config-prettier: ^10.1.8
  eslint-plugin-import: ^2.32.0
  eslint-plugin-no-only-tests: ^3.3.0
  eslint-plugin-simple-import-sort: ^12.1.1
  eslint-plugin-unused-imports: ^4.2.0
  ethers: ^6.15.0
  glob: ^11.0.2
  globals: ^16.4.0
  hardhat: ^2.26.0
  hardhat-contract-sizer: ^2.10.0
  hardhat-dependency-compiler: ^1.2.1
  hardhat-gas-reporter: ^1.0.8
  hardhat-secure-accounts: ^1.0.5
  hardhat-storage-layout: ^0.1.7
  husky: ^9.1.7
  json5: ^2.2.3
  lint-staged: ^16.2.4
  markdownlint-cli: ^0.45.0
  mocha: ^11.7.1
  prettier: ^3.6.2
  prettier-plugin-solidity: ^2.1.0
  solhint: ^6.0.1
  ts-node: ^10.9.2
  typechain: ^8.3.2
  typescript: ^5.9.3
  typescript-eslint: ^8.46.1
  viem: ^2.31.7
  yaml-lint: ^1.7.0
