#!/bin/bash

# This script builds WAGMI and ethers-v5 types for interacting with the contracts
# Note that ethers-v6 types are automatically generated by hardhat compilation step
# - wagmi: wagmi/
# - ethers-v5: types-v5/
# - ethers-v6: types/

# Build wagmi types
pnpm wagmi generate

# Build ethers-v5 types
pnpm typechain \
  --target ethers-v5 \
  --out-dir types-v5 \
  'artifacts/contracts/**/!(*.dbg).json' \
  'artifacts/@openzeppelin/**/!(*.dbg).json'