services:
  dev-graph-contracts:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - /opt/configs/graphprotocol/contracts.env
    environment:
      # Essential for large builds
      - NODE_OPTIONS=--max-old-space-size=4096

      # Clean development environment
      - PYTHONDONTWRITEBYTECODE=1

      # Standard user directories
      - XDG_CACHE_HOME=/home/vscode/.cache
      - XDG_CONFIG_HOME=/home/vscode/.config
      - XDG_DATA_HOME=/home/vscode/.local/share

      # Safe caches (won't cause cross-branch issues)
      - GH_CONFIG_DIR=/home/vscode/.cache/github
      - PIP_CACHE_DIR=/home/vscode/.cache/pip

      # Note: NPM, Yarn, Foundry, and Solidity caches are intentionally not set
      # to avoid cross-branch contamination. Tools will use their default locations.
    volumes:
      # Git repo root
      - /git:/git

      # Local directories for user data (keep local to container)
      - vscode-cache:/home/vscode/.cache
      - vscode-config:/home/vscode/.config
      - vscode-data:/home/vscode/.local/share
      - vscode-bin:/home/vscode/.local/bin

volumes:
  vscode-cache:
  vscode-config:
  vscode-data:
  vscode-bin:
