services:
  dev-graph-contracts:
    build:
      context: .
      dockerfile: Dockerfile
    user: vscode
    env_file:
      - /opt/configs/graphprotocol/contracts.env
    environment:
      # Essential for large builds
      - NODE_OPTIONS=--max-old-space-size=4096

      # Clean development environment
      - PYTHONDONTWRITEBYTECODE=1

      # Disable interactive prompts
      - COREPACK_ENABLE_DOWNLOAD_PROMPT=0

      # Standard user directories
      - XDG_CACHE_HOME=/home/vscode/.cache
      - XDG_CONFIG_HOME=/home/vscode/.config
      - XDG_DATA_HOME=/home/vscode/.local/share

      # Safe caches (won't cause cross-branch issues)
      - GH_CONFIG_DIR=/home/vscode/.cache/github
      - PIP_CACHE_DIR=/home/vscode/.cache/pip

      # pnpm cache is safe to share due to content-addressable storage
      # PNPM_HOME is for global packages and should be user-specific (uses default)
      - PNPM_STORE_DIR=/home/vscode/.cache/pnpm/store
      # Note: NPM, Foundry, and Solidity caches are intentionally not set
      # to avoid cross-branch contamination. Tools will use their default locations.
    volumes:
      # Git repo root
      - /git:/git

      # Cached directories
      - vscode-config:/home/vscode/.config
      - vscode-data:/home/vscode/.local/share
      - vscode-bin:/home/vscode/.local/bin
      - vscode-cache:/home/vscode/.cache
      # Global pnpm store (content-addressable cache only)
      - global-pnpm-cache:/home/vscode/.cache/pnpm

volumes:
  vscode-cache:
  vscode-config:
  vscode-data:
  vscode-bin:
  global-pnpm-cache:
    external: true
