services:
  dev-graph-contracts:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - /opt/configs/graphprotocol/contracts.env
    environment:
      # Essential for large builds
      - NODE_OPTIONS=--max-old-space-size=4096

      # Clean development environment
      - PYTHONDONTWRITEBYTECODE=1

      # Disable interactive prompts
      - COREPACK_ENABLE_DOWNLOAD_PROMPT=0

    volumes:
      # Git repo root
      - /git:/git
