/**
 * Auto-generated interface IDs from Solidity compilation
 *
 * DO NOT EDIT THIS FILE MANUALLY!
 *
 * This file is automatically generated by running:
 * node scripts/generateInterfaceIds.js
 *
 * To add a new interface ID:
 * 1. Add the interface to the INTERFACES object in scripts/generateInterfaceIds.js
 * 2. Ensure contracts are compiled: pnpm hardhat compile
 * 3. Run the generation script above
 */

export const INTERFACE_IDS = {
  IERC165: '0x01ffc9a7',
  IRewardsManager: '0x0d63a8cd',
} as const

// Individual exports for convenience
export const IERC165 = INTERFACE_IDS.IERC165
export const IRewardsManager = INTERFACE_IDS.IRewardsManager
