/**
 * Auto-generated interface IDs from Solidity compilation
 *
 * DO NOT EDIT THIS FILE MANUALLY!
 *
 * This file is automatically generated by running:
 * pnpm hardhat run scripts/generateInterfaceIds.js --network hardhat
 *
 * To add a new interface ID:
 * 1. Add the interface import and getter method to contracts/utils/InterfaceIdExtractor.sol
 * 2. Run the generation script above
 */

export const INTERFACE_IDS = {
  IERC165: '0x01ffc9a7',
  IIssuanceAllocationAdministration: '0x36759695',
  IIssuanceAllocationDistribution: '0x79da37fc',
  IIssuanceAllocationStatus: '0xc0ba8a55',
  IIssuanceTarget: '0xaee4dc43',
  IRewardsEligibilityAdministration: '0x9a69f6aa',
  IRewardsEligibility: '0x66e305fd',
  IRewardsEligibilityReporting: '0x38b7c077',
  IRewardsEligibilityStatus: '0x53740f19',
  IRewardsManager: '0xa31d8306',
} as const

// Individual exports for convenience
export const IERC165 = INTERFACE_IDS.IERC165
export const IIssuanceAllocationAdministration = INTERFACE_IDS.IIssuanceAllocationAdministration
export const IIssuanceAllocationDistribution = INTERFACE_IDS.IIssuanceAllocationDistribution
export const IIssuanceAllocationStatus = INTERFACE_IDS.IIssuanceAllocationStatus
export const IIssuanceTarget = INTERFACE_IDS.IIssuanceTarget
export const IRewardsEligibilityAdministration = INTERFACE_IDS.IRewardsEligibilityAdministration
export const IRewardsEligibility = INTERFACE_IDS.IRewardsEligibility
export const IRewardsEligibilityReporting = INTERFACE_IDS.IRewardsEligibilityReporting
export const IRewardsEligibilityStatus = INTERFACE_IDS.IRewardsEligibilityStatus
export const IRewardsManager = INTERFACE_IDS.IRewardsManager
