#!/bin/bash

set -eo pipefail
source $(pwd)/scripts/evm

MNEMONIC="myth like bonus scare over problem client lizard pioneer submit female collect"
GRAPH_CONFIG="config/graph.localhost.yml"

### Setup
# Compile contracts
yarn build

# Start evm
evm_kill
evm_start
sleep 5

# Deploy protocol
npx hardhat migrate --network localhost --skip-confirmation --graph-config "$GRAPH_CONFIG"


### Test
# Run tests using the localhost evm instance and the localhost graph config
GRAPH_CONFIG='config/graph.localhost.yml' npx hardhat test e2e/*.ts --network localhost


### Cleanup
# Exit error mode so the evm instance always gets killed
set +e
result=0

evm_kill
exit $result
