#!/bin/bash

OUT_DIR="build/flatten"

mkdir -p ${OUT_DIR}

echo "Flattening contracts..."

FILES=(
    "contracts/discovery/GNS.sol"
    "contracts/discovery/ServiceRegistry.sol"
    "contracts/curation/Curation.sol"
    "contracts/curation/GraphSignalToken.sol"
    "contracts/staking/Staking.sol"
    "contracts/rewards/RewardsManager.sol"
    "contracts/token/GraphToken.sol"
    "contracts/epochs/EpochManager.sol"
    "contracts/upgrades/GraphProxy.sol"
)

for path in ${FILES[@]}; do
    IFS='/'
    parts=( $path )
    name=${parts[${#parts[@]}-1]}
    echo "Flatten > ${name}"
    truffle-flattener "${path}" > "${OUT_DIR}/${name}"
done

echo "Done!"
