#!/bin/bash

cat addresses.json |
    jq '."1"."IENS".address = "0x00000000000C2E074eC69A0dFb2997BA6C7d2e1e"' |
    jq '."5"."IENS".address = "0x00000000000C2E074eC69A0dFb2997BA6C7d2e1e"' |
    jq '."1"."IEthereumDIDRegistry".address = "0xdCa7EF03e98e0DC2B855bE647C39ABe984fcF21B"' |
    jq '."5"."IEthereumDIDRegistry".address = "0xdCa7EF03e98e0DC2B855bE647C39ABe984fcF21B"' > addresses.json.tmp
mv addresses.json.tmp addresses.json
