#!/bin/bash

cat addresses.json |
    jq '."1"."IENS".address = "0x00000000000C2E074eC69A0dFb2997BA6C7d2e1e"' |
    jq '."4"."IENS".address = "0x00000000000C2E074eC69A0dFb2997BA6C7d2e1e"' > addresses.json.tmp
mv addresses.json.tmp addresses.json
