#!/bin/bash

TYPECHAIN_DIR=dist/typechain

set -eo pipefail

# Build contracts
npm run clean
npm run build

# Refresh distribution folder
rm -rf dist && mkdir -p dist
cp -R build/abis build/contracts build/typechain dist

### Build Typechain bindings

# Move sources to a different folder
mv ${TYPECHAIN_DIR}/contracts ${TYPECHAIN_DIR}/_src
# Build and create TS declarations
tsc -d ${TYPECHAIN_DIR}/_src/*.ts --outdir ${TYPECHAIN_DIR}/contracts
# Copy back sources
cp ${TYPECHAIN_DIR}/_src/*.ts ${TYPECHAIN_DIR}/contracts
# Copy conflicting definition files
cp ${TYPECHAIN_DIR}/_src/ProxyFactory.d.ts ${TYPECHAIN_DIR}/contracts
# Delete temporary src dir
rm -rf ${TYPECHAIN_DIR}/_src
