#!/bin/bash

set -eo pipefail
source $(pwd)/scripts/evm

### Setup EVM

# Ensure we compiled sources

yarn build

### Cleanup
function cleanup() {
  if [ "$RUN_EVM" = true ]; then
    evm_kill
  fi
}
trap cleanup EXIT

# Gas reporter needs to run in its own evm instance
if [ "$RUN_EVM" = true  ]; then
  evm_kill
  evm_start
  sleep 5
fi

### Main

mkdir -p reports

# Run using the standalone evm instance
npx hardhat test --network hardhat $@

if [ "$REPORT_GAS" = true ]; then
  cat reports/gas-report.log
  echo "" # Gas report doesn't have a newline at the end
fi
