#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# contracts
pushd packages/contracts
npx --no-install lint-staged
popd

# subgraph service
pushd packages/subgraph-service
npx --no-install lint-staged
popd
