sources:
  - name: graph-network
    handler:
      graphql:
        endpoint: https://gateway.thegraph.com/api/${STUDIO_API_KEY}/subgraphs/id/9Co7EQe5PgW3ugCUJrJgRv4u9zdEuDJf8NvMWftNsBH8
        retry: 5

  - name: token-distribution
    handler:
      graphql:
        endpoint: https://gateway.thegraph.com/api/${STUDIO_API_KEY}/subgraphs/id/ChfAJn6jQEBjVqtdUiThfG6sWy2Sr5XQPNucE9DkgXSN
        retry: 5
    transforms:
      - autoPagination:
          validateSchema: true

documents:
  - ops/queries/account.graphql
  - ops/queries/curators.graphql
  - ops/queries/network.graphql
  - ops/queries/tokenLockWallets.graphql
